[workspace]
channels = ["conda-forge"]
name = "memristor_simulation"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
migrate = "python manage.py migrate"
static = "python manage.py collectstatic --noinput"
admin = "python manage.py createsuperuser"
setup-db = { depends-on = ["migrate", "static"] }
server = "python manage.py runserver"

[dependencies]
python = "==3.10"
numpy = "==1.24.3"
pandas = "==2.0.2"
matplotlib = "==3.7.1"
networkx = "==3.1"
scipy = "==1.14.1"
django = "==5.1.6"
djangorestframework = "==3.15.2"
pytest = "==8.3.4"
pytest-django = "==4.8.0"
pytest-cov = "==5.0.0"
python-dotenv = "==1.1.1"
ngspice = ">=41,<42"

[pypi-dependencies]
django-rest-enumfield = "==0.2.0"
